version: 2

jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install --prefix ./client-ts
      - run:
        name: Run tests
        command: npm test --prefix ./client-ts
  deploy:
    machine:
      enabled: true
    working_directory: ~/tmp
    steps:
      - checkout
      - run: echo "hello world"
workflows:
  version: 2
  build-test-and-approve-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
          - build
      - deploy:
          requires:
          - hold