version: 2.1

jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install --prefix ./client-ts
      - run:
          name: Run tests
          command: npm test --prefix ./client-ts
  deploy:
    machine:
      enabled: true
    working_directory: ~/tmp
    steps:
      - checkout
      - when:
          condition:
            or:
              - equal: [ staging, << pipeline.git.branch >> ]
          steps:
            - run: 
                name: Deploy
                command: |
                  echo "I am on << pipeline.git.branch >>"
                  git remote add live ssh://madisons@madisonsreport.com/var/repo/staging.madisonsreport.git
                  git push live staging
                  
workflows:
  version: 2.1
  build-test-and-approve-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
          - build
      - deploy:
          requires:
          - hold