version: 2

jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install --prefix ./client-ts
      - run:
          name: Run tests
          command: npm test --prefix ./client-ts
  deploy:
    machine:
      enabled: true
    working_directory: ~/tmp
    steps:
      - checkout
      - when:
        condition:
          equal: [ master, << pipeline.git.branch >> ]
        steps:
          - run: 
              name: Deploy to master
              command: |
                echo "I am on master"
      - when:
          condition:
            equal: [ staging, << pipeline.git.branch >> ]
          steps:
            - run: 
                name: Deploy to staging
                command: |
                  echo "I am on staging"
                  git remote add live ssh://madisons@madisonsreport.com/var/repo/staging.madisonsreport.git
                  git push live staging
workflows:
  version: 2
  build-test-and-approve-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
          - build
      - deploy:
          requires:
          - hold