version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: cd client
      - run: yarn install
      - run: yarn test