version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install --prefix ./client-ts
      - run: npm test --prefix ./client-ts