const orderedSections = [
  'Name',
  'Type',
  'Region',
  'Address',
  'Location',
  'Phone',
  'Fax',
  'Email',
  'Website',
  'Contact Persons',
  'Species',
  'Products',
  'Rough Sizes',
  'Surfaced Sizes',
  'Production',
  'Panel Thickness',
  'Services',
  'Kiln Capacity',
  'Shipping',
  'Export',
  'Grading Agency',
  'Member Of',
  'Employees',
  'Notes',
  'Certification',
  'Preservatives',
  'Treating Facilities',
  'Distribution Yard',
  'Mill Status'
];

export default orderedSections;